
[origins]

	[origins."origins:shulk"]
		"origins:strong_arms" = true
		"origins:no_shield" = true
		"origins:more_exhaustion" = true
		"origins:strong_arms_break_speed" = true
		"origins:natural_armor" = true
		enabled = true
		"origins:shulker_inventory" = true

	[origins."origins:merling"]
		"origins:air_from_potions" = true
		"origins:swim_speed" = true
		"origins:water_vision" = true
		"origins:like_water" = true
		"origins:aqua_affinity" = true
		"origins:water_breathing" = true
		"origins:conduit_power_on_land" = true
		enabled = true
		"origins:aquatic" = true

	[origins."origins:arachnid"]
		"origins:carnivore" = true
		"origins:fragile" = true
		"origins:arthropod" = true
		"origins:master_of_webs" = true
		enabled = true
		"origins:climbing" = true

	[origins."origins:phantom"]
		"origins:phasing" = true
		"origins:fragile" = true
		"origins:phantomize" = true
		"origins:translucent" = true
		"origins:invisibility" = true
		"origins:hunger_over_time" = true
		enabled = true
		"origins:burn_in_daylight" = true
		"origins:phantomize_overlay" = true

	[origins."origins:enderian"]
		"origins:water_vulnerability" = true
		"origins:throw_ender_pearl" = true
		"origins:pumpkin_hate" = true
		"origins:ender_particles" = true
		"origins:damage_from_potions" = true
		enabled = true
		"origins:extra_reach" = true

	[origins."origins:blazeborn"]
		"origins:water_vulnerability" = true
		"origins:flame_particles" = true
		"origins:burning_wrath" = true
		"origins:hotblooded" = true
		"origins:fire_immunity" = true
		"origins:damage_from_snowballs" = true
		"origins:nether_spawn" = true
		"origins:damage_from_potions" = true
		enabled = true

	[origins."origins:feline"]
		"origins:cat_vision" = true
		"origins:velvet_paws" = true
		"origins:fall_immunity" = true
		"origins:weak_arms" = true
		"origins:nine_lives" = true
		enabled = true
		"origins:sprint_jump" = true
		"origins:scare_creepers" = true

	[origins."origins:elytrian"]
		"origins:more_kinetic_damage" = true
		"origins:elytra" = true
		"origins:claustrophobia" = true
		"origins:aerial_combatant" = true
		"origins:light_armor" = true
		"origins:launch_into_air" = true
		enabled = true

	[origins."origins:human"]
		enabled = true

	[origins."origins:avian"]
		"origins:fresh_air" = true
		"origins:vegetarian" = true
		"origins:lay_eggs" = true
		"origins:slow_falling" = true
		"origins:tailwind" = true
		"origins:like_air" = true
		enabled = true

	[origins."eidolonorigins:palladin"]
		enabled = true
		"medievalorigins:yeti/frigid_pulse" = true
		"medievalorigins:yeti/from_whence_you_came" = true
		"medievalorigins:yeti/frosty_breath" = true
		"medievalorigins:yeti/titanic" = true
		"medievalorigins:yeti/unstoppable" = true
		"medievalorigins:yeti/winter_body" = true
		"medievalorigins:yeti/flammable" = true
		"medievalorigins:yeti/thick_fur" = true
		"medievalorigins:yeti/spell_power" = true
		"origins_env_deh:cold_resistance" = true
		"thermoo-patches:cold_immune" = true
		"origins_survive:cold_resistance" = true
		"origins_toughasnails:cold_resistance" = true

	[origins."eidolonorigins:lych"]
		enabled = true
		"medievalorigins:wood_elf/archer" = true
		"medievalorigins:wood_elf/forest_vision" = true
		"medievalorigins:wood_elf/empowered_shot" = true
		"medievalorigins:wood_elf/empowered_shot_zenith" = true
		"medievalorigins:wood_elf/empowered_shot_apotheosis" = true
		"medievalorigins:wood_elf/eagle_eyed" = true
		"medievalorigins:wood_elf/towering" = true
		"medievalorigins:wood_elf/steward" = true
		"medievalorigins:wood_elf/elegant" = true
		"medievalorigins:wood_elf/graceful" = true
		"medievalorigins:wood_elf/gear_spawn" = true
		"medievalorigins:wood_elf/spell_power" = true
		"eidolonorigins:lych/no_armor" = true

	[origins."eidolon_origins:palladin"]
		enabled = true
		"medievalorigins:yeti/frigid_pulse" = true
		"medievalorigins:yeti/from_whence_you_came" = true
		"medievalorigins:yeti/frosty_breath" = true
		"medievalorigins:yeti/titanic" = true
		"medievalorigins:yeti/unstoppable" = true
		"medievalorigins:yeti/winter_body" = true
		"medievalorigins:yeti/flammable" = true
		"medievalorigins:yeti/thick_fur" = true
		"medievalorigins:yeti/spell_power" = true
		"origins_env_deh:cold_resistance" = true
		"thermoo-patches:cold_immune" = true
		"origins_survive:cold_resistance" = true
		"origins_toughasnails:cold_resistance" = true

	[origins."eidolon_origins:lych"]
		enabled = true
		"eidolon_origins:lych/no_armor" = true
		"medievalorigins:wood_elf/forest_vision" = true
		"medievalorigins:wood_elf/empowered_shot" = true
		"medievalorigins:wood_elf/empowered_shot_zenith" = true
		"medievalorigins:wood_elf/empowered_shot_apotheosis" = true
		"medievalorigins:wood_elf/eagle_eyed" = true
		"medievalorigins:wood_elf/towering" = true
		"medievalorigins:wood_elf/steward" = true
		"medievalorigins:wood_elf/elegant" = true
		"medievalorigins:wood_elf/graceful" = true
		"medievalorigins:wood_elf/gear_spawn" = true
		"medievalorigins:wood_elf/spell_power" = true
		"eidolon_origins:lych/fragile" = true
		"eidolon_origins:lych/aggressive_golems" = true
		"eidolon_origins:lych/no_trades" = true
		"eidolon_origins:lych/silver_items_burn" = true
		"eidolon_origins:lych/ash" = true
		"eidolon_origins:lych/ash_two" = true
		"minecraft:eidolon_origins/lych/undead" = true
		"eidolon_origins:lych/undead" = true
		"eidolon_origins:lych/damage_taken" = true
		"eidolon_origins:lych/damage_dealt" = true
		"eidolon_origins:lyck/no_holy_items" = true
		"eidolon_origins:lych/no_holy_items" = true
		"eidolon_origins:lych/general/undead" = true
		"eidolon_origins:lych/general/fragile" = true
		"eidolon_origins:lych/general/no_armor" = true
		"eidolon_origins:lych/general/aggressive_golems" = true
		"eidolon_origins:lych/general/no_trades" = true
		"eidolon_origins:lych/general/silver_items_burn" = true
		"eidolon_origins:lych/general/ash" = true
		"eidolon_origins:lych/generaldamage_taken" = true
		"eidolon_origins:lych/general/damage_dealt" = true
		"eidolon_origins:lych/general/no_holy_items" = true
		"eidolon_origins:lych/general/damage_taken" = true
		"eidolon_origins:lych/tier_one/undeadge" = true
		"eidolon_origins:lych/general/undeadge" = true
		"eidolon_origins:lych/tier_one/neutral_undead_enemies" = true

